name: Add Issues To Projects

on:
  issues:
    types: 
      - opened

jobs:
  add-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3eb77c7243b85c65e84acfa93fdbac02fb6bd532
        with:
          app_id: ${{ secrets.ALPHA_BOT_ID }}
          private_key: ${{ secrets.ALPHA_BOT_PEM }}

      - name: Add Alpha Bug Issue To project
        uses: actions/add-to-project@v0.6.1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          project-url: https://github.com/orgs/IceWhaleTech/projects/5
          labeled: alpha, bug
          label-operator: AND
          
      - name: Add App Request Issue To project
        uses: actions/add-to-project@v0.6.1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          project-url: https://github.com/orgs/IceWhaleTech/projects/8
          labeled: "App Request"
          label-operator: AND
