# This is a basic workflow to help you get started with Actions

name: Move alpha bug to project

on:
  issues:
    types: 
      - opened

jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3eb77c7243b85c65e84acfa93fdbac02fb6bd532
        with:
          app_id: ${{ secrets.ALPHA_BOT_ID }}
          private_key: ${{ secrets.ALPHA_BOT_PEM }}

      - name: Add Issue To GitHub Projects Beta
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/IceWhaleTech/projects/5
          github-token: ${{ steps.generate_token.outputs.token }}
          labeled: alpha, bug
          label-operator: AND
